name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


defaults:
  run:
    shell: bash -el {0}

jobs:
  tests:
    name: Micromamba test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
      - run: pip install . --no-deps --no-build-isolation
      - run: python -c 'import my_package'